(()=>{
'use strict';
if(window.__compositionLabComparisonAdapter)return;
window.__compositionLabComparisonAdapter=true;
const $=id=>document.getElementById(id);
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const src={A:null,B:null},names={A:'',B:''};
let lastAnswer='';

function compositions(){
  try{if(window.CompositionLabStorage?.loadCompositions)return window.CompositionLabStorage.loadCompositions().map(x=>({score:x.score,title:x.score?.ti||'Komposition'}));}catch(_){}
  try{return JSON.parse(localStorage.getItem('ai_midi_composer_history_v37')||'[]').map(x=>({score:x.score,title:x.title||x.score?.ti||'Komposition'}));}catch(_){return[]}
}
function templates(){
  try{if(window.CompositionLabExperiment?.loadHistory)return window.CompositionLabExperiment.loadHistory().map(x=>({score:x.score,title:x.score?.ti||'Vorlage'}));}catch(_){}
  try{return JSON.parse(localStorage.getItem('composition_lab_experiment_history_v1')||'[]').map(x=>({score:x.score,title:x.title||x.score?.ti||'Vorlage'}));}catch(_){return[]}
}
function fill(){
  const h=compositions(),e=templates();
  ['A','B'].forEach(w=>{const sel=$('source'+w+'Select');if(!sel)return;const old=sel.value;sel.innerHTML='<option value="">Quelle wählen …</option>';h.forEach((it,i)=>{const o=document.createElement('option');o.value='h:'+i;o.textContent='Komposition · '+(it.title||'Ohne Titel');sel.appendChild(o)});e.forEach((it,i)=>{const o=document.createElement('option');o.value='e:'+i;o.textContent='Vorlage · '+(it.title||'Vorlage');sel.appendChild(o)});if([...sel.options].some(o=>o.value===old))sel.value=old;});
}
function card(w){const b=$('source'+w+'Card'),x=src[w];if(!b)return;if(!x){b.textContent='Noch keine Quelle geladen.';return}const n=(x.tr||[]).reduce((a,t)=>a+(t.nt?.length||0),0);b.innerHTML=`<strong>${esc(names[w]||x.ti||('Quelle '+w))}</strong><div class="historymeta">${esc(x.bpm||'')} BPM · ${esc(x.k||'')} · ${x.tr?.length||0} Spur(en) · ${n} Noten</div>${x.sm?`<div style="margin-top:6px;font-size:12px;color:var(--muted);">${esc(String(x.sm)).slice(0,300)}</div>`:''}`}
function choose(w,v){if(!v){src[w]=null;names[w]='';card(w);return}const [kind,ix]=v.split(':');const it=(kind==='h'?compositions():templates())[Number(ix)];if(!it?.score)return;src[w]=clone(it.score);names[w]=it.title||it.score.ti||('Quelle '+w);card(w)}
async function file(w,f){if(!f)return;try{const io=window.CompositionLabMIDI;src[w]=f.name.toLowerCase().endsWith('.json')?JSON.parse(await f.text()):(io?.parse?io.parse(await f.arrayBuffer()):parseUploadedMidi(await f.arrayBuffer()));names[w]=f.name;card(w)}catch(e){const b=$('source'+w+'Card');if(b)b.innerHTML=`<span class="err">${esc(e?.message||e)}</span>`}}
function creds(){return{provider:$('provider')?.value||'',model:$('model')?.value||'',key:$('apiKey')?.value?.trim()||''}}
async function compare(makePrompt=false){if(!src.A||!src.B)throw new Error('Bitte zuerst Quelle A und Quelle B laden.');const {provider,model,key}=creds();if(!key)throw new Error('API-Key fehlt.');const task=makePrompt?'Erstelle aus dem Vergleich einen kurzen, konkreten und editierbaren Kompositionsauftrag. Benenne klar, welche 1–2 Merkmale aus Quelle A und welche 1–2 Merkmale aus Quelle B übernommen oder weiterentwickelt werden sollen. Maximal etwa 120 Wörter. Das Ergebnis soll ein eigenständiges neues Stück C ermöglichen.':'Vergleiche beide musikalischen Quellen kurz und musikalisch. Maximal etwa 220 Wörter. Keine technische Detailanalyse. Gliedere nur in: 1. Quelle A – charakteristische Idee und stärkste Merkmale, 2. Quelle B – charakteristische Idee und stärkste Merkmale, 3. wichtigste Unterschiede, 4. zwei oder drei besonders sinnvolle Möglichkeiten der Kombination. Keine bloße Siegerwertung.';const text=`${task}\n\nQUELLE A – ${names.A||src.A.ti||'A'}:\n${JSON.stringify(src.A)}\n\nQUELLE B – ${names.B||src.B.ti||'B'}:\n${JSON.stringify(src.B)}`;const system=(typeof SYSTEM_PREFIX!=='undefined'&&SYSTEM_PREFIX)?SYSTEM_PREFIX:'Du bist ein musikalischer Analyse- und Kompositionsassistent.';const r=await callLLM(provider,model,key,system,text,false);return String(r?.text||r||'').trim()}
function addChat(role,text){const log=$('sourceChatLog');if(!log)return;const d=document.createElement('div');d.className='chatmsg '+(role==='user'?'chatuser':'chatai');d.textContent=(role==='user'?'Du: ':'KI: ')+text;log.appendChild(d);log.scrollTop=log.scrollHeight}
async function askChat(){const input=$('sourceChatInput'),send=$('sourceChatSendBtn');const msg=String(input?.value||'').trim();if(!msg)return;if(!src.A&&!src.B){addChat('ai','Bitte zuerst mindestens eine Quelle laden.');return}const {provider,model,key}=creds();if(!key){addChat('ai','Bitte zuerst den API-Key der gewählten KI eingeben.');return}addChat('user',msg);input.value='';send.disabled=true;send.textContent='KI denkt …';try{const parts=[];if(src.A)parts.push(`QUELLE A – ${names.A||src.A.ti||'A'}:\n${JSON.stringify(src.A)}`);if(src.B)parts.push(`QUELLE B – ${names.B||src.B.ti||'B'}:\n${JSON.stringify(src.B)}`);const task=`Der Nutzer untersucht musikalisches Material im Vergleichslabor. Beantworte seine konkrete Frage musikalisch und direkt. Verwende nur die geladenen Quellen. Wenn er eine Synthese oder Weiterentwicklung verlangt, entwickle einen freien musikalischen Vorschlag ohne unnötigen technischen Bauplan.\n\nNUTZERFRAGE:\n${msg}\n\n${parts.join('\n\n')}`;const system=(typeof SYSTEM_PREFIX!=='undefined'&&SYSTEM_PREFIX)?SYSTEM_PREFIX:'Du bist ein musikalischer Analyse- und Kompositionsassistent.';const r=await callLLM(provider,model,key,system,task,false);lastAnswer=String(r?.text||r||'').trim();addChat('ai',lastAnswer||'Keine Antwort erhalten.');const use=$('sourceChatUseBtn');if(use)use.disabled=!lastAnswer}catch(e){addChat('ai','Fehler: '+(e?.message||e))}finally{send.disabled=false;send.textContent='Senden'}}
function fresh(id,handler,event='click'){const old=$(id);if(!old)return null;const n=old.cloneNode(true);old.replaceWith(n);n.addEventListener(event,handler);return n}
function install(){if(!$('sourceASelect')||!$('sourceBSelect'))return false;['A','B'].forEach(w=>{fresh('source'+w+'Select',e=>choose(w,e.currentTarget.value),'change');fresh('source'+w+'File',e=>file(w,e.currentTarget.files?.[0]),'change')});fresh('aiCompareBtn',async()=>{const b=$('aiCompareResult');try{b.textContent='KI analysiert A und B …';b.textContent=await compare(false)}catch(e){b.innerHTML=`<span class="err">${esc(e?.message||e)}</span>`}});fresh('suggestSynthesisBtn',async()=>{const p=$('synthesisPrompt'),b=$('aiCompareResult');try{p.value='KI erstellt Syntheseauftrag …';p.value=await compare(true)}catch(e){p.value='';b.innerHTML=`<span class="err">${esc(e?.message||e)}</span>`}});fresh('useSynthesisBtn',()=>{const p=$('synthesisPrompt'),out=$('prompt'),b=$('aiCompareResult');if(!src.A||!src.B){b.innerHTML='<span class="err">Bitte zuerst A und B laden.</span>';return}const t=String(p?.value||'').trim();if(!t){b.innerHTML='<span class="err">Bitte zuerst einen Syntheseauftrag formulieren.</span>';return}if(out)out.value=t;window.comparisonSynthesisSources={a:clone(src.A),b:clone(src.B),nameA:names.A,nameB:names.B};try{saveCurrentState?.()}catch(_){}const st=$('status');if(st)st.innerHTML='<span class="ok">Syntheseauftrag übernommen. Quelle A und B werden beim nächsten Komponieren gemeinsam an die KI übergeben.</span>'});fresh('sourceChatSendBtn',askChat);const input=fresh('sourceChatInput',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();askChat()}},'keydown');if(input){input.disabled=false;input.readOnly=false}fresh('sourceChatUseBtn',()=>{if(!lastAnswer)return;const p=$('prompt');if(p)p.value=lastAnswer;try{saveCurrentState?.()}catch(_){} });window.compositionLabGetComparisonSource=w=>src[w]||null;window.compositionLabRefreshComparisonSources=fill;fill();return true}
let n=0,t=setInterval(()=>{if(install()||++n>120)clearInterval(t)},100);
})();