(()=>{
'use strict';
if(window.__compositionLabPlayerAdapter)return;
window.__compositionLabPlayerAdapter=true;
const $=id=>document.getElementById(id);
const VERSION='player-adapter-1.0';
const LOOKAHEAD_SEC=.30,TICK_MS=80;
let timer=0,raf=0,token=0,activeScore=null,activeStartBeat=0,activeMaxBeat=0,activeBpm=96,activeSpb=.625,baseTime=0,events=[],cursor=0,activeTarget='main';
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};
const maxBeat=sc=>{try{return typeof scoreMaxBeat==='function'?scoreMaxBeat(sc):Math.max(0,...(sc?.tr||[]).flatMap(t=>(t.nt||[]).map(n=>(Number(n[0])||0)+(Number(n[1])||0)*Math.max(.05,Number(n[5]??.95)||.95))))}catch(_){return 0}};
function currentBeat(){if(!activeScore)return 0;try{const ac=playerAudioCtx;if(!ac)return activeStartBeat;return Math.min(activeMaxBeat,activeStartBeat+Math.max(0,ac.currentTime-baseTime)*activeBpm/60)}catch(_){return activeStartBeat}}
function status(msg){const e=$('playerStatus');if(e)e.textContent=msg}
function clearLocal(){token++;if(timer){clearTimeout(timer);timer=0}if(raf){cancelAnimationFrame(raf);raf=0}events=[];cursor=0;activeScore=null}
function stopInstruments(){try{playerInstrumentCache?.forEach?.(p=>Promise.resolve(p).then(inst=>{try{inst.stop()}catch(_){}}).catch(()=>{}))}catch(_){}}
function resetTimes(){[['playerSeek','playerTime'],['templateSeek','templateTime'],['seekSourceA','timeSourceA'],['seekSourceB','timeSourceB']].forEach(([r,t])=>{if($(r))$(r).value='0';if($(t))$(t).textContent='0:00 / 0:00'})}
function consolidatedStop(update=true){clearLocal();stopInstruments();try{playerPlaying=false;playerPaused=false}catch(_){}if(update)status('Gestoppt.')}
function makeEvents(score,fromBeat){const out=[];for(const t of score?.tr||[]){const ch=Math.max(0,Math.min(15,Number(t.ch)||0)),pg=Math.max(0,Math.min(127,Number(t.pg)||0));for(const n of t.nt||[]){if(!Array.isArray(n))continue;const st=Number(n[0])||0,d=Math.max(.02,Number(n[1])||.25),gate=Math.max(.05,Math.min(4,Number(n[5]??.95)||.95)),end=st+d*gate;if(end<=fromBeat)continue;out.push({beat:Math.max(st,fromBeat),end,pitch:Math.max(0,Math.min(127,Math.round(Number(n[2])||60))),velocity:Math.max(1,Math.min(127,Number(n[3])||80)),pg,ch})}}out.sort((a,b)=>a.beat-b.beat||a.ch-b.ch||a.pitch-b.pitch);return out}
async function preload(score){const used=[],seen=new Set();for(const t of score?.tr||[]){const ch=Math.max(0,Math.min(15,Number(t.ch)||0)),pg=Math.max(0,Math.min(127,Number(t.pg)||0)),key=ch===9?'d':pg+':'+ch;if(!seen.has(key)){seen.add(key);used.push([pg,ch])}}await Promise.all(used.map(([pg,ch])=>loadGMInstrument(pg,ch)))}
async function scheduleWindow(myToken){if(myToken!==token||!activeScore||playerPaused)return;const ac=playerAudioCtx;if(!ac)return;const nowBeat=currentBeat(),limit=nowBeat+LOOKAHEAD_SEC*activeBpm/60;while(cursor<events.length&&events[cursor].beat<=limit){const e=events[cursor++],inst=await loadGMInstrument(e.pg,e.ch);if(myToken!==token)return;const startBeat=Math.max(e.beat,nowBeat),when=ac.currentTime+Math.max(.01,(startBeat-nowBeat)*activeSpb),dur=Math.max(.03,(e.end-startBeat)*activeSpb);try{inst.play(e.pitch,when,{duration:dur,gain:Math.max(.02,Math.min(1,e.velocity/127))})}catch(_){}}if(myToken===token&&activeScore)timer=setTimeout(()=>scheduleWindow(myToken).catch(err=>status('Player-Fehler: '+(err?.message||err))),TICK_MS)}
function updateUi(){if(!activeScore)return;const beat=currentBeat(),frac=activeMaxBeat?beat/activeMaxBeat:0,total=activeMaxBeat*activeSpb,now=beat*activeSpb;const pairs=activeTarget==='main'?[['playerSeek','playerTime']]:activeTarget==='template'?[['templateSeek','templateTime']]:activeTarget==='A'?[['seekSourceA','timeSourceA']]:[['seekSourceB','timeSourceB']];for(const [r,t] of pairs){if($(r))$(r).value=String(Math.round(frac*1000));if($(t))$(t).textContent=`${fmt(now)} / ${fmt(total)}`};if(beat>=activeMaxBeat-.001){if(playerLoopEnabled){const sc=activeScore,target=activeTarget;consolidatedStop(false);consolidatedPlay(sc,0,target).catch(err=>status('Player-Fehler: '+(err?.message||err)));return}playerPlaying=false;activeScore=null;status('Wiedergabe beendet.');return}raf=requestAnimationFrame(updateUi)}
async function consolidatedPlay(score,fromBeat=0,target='main'){if(!score||!Array.isArray(score.tr)||!score.tr.length){status('Noch keine Komposition zum Abspielen.');return}const ac=ensurePlayerAudio();if(ac.state==='suspended')await ac.resume();consolidatedStop(false);activeScore=score;activeTarget=target;activeStartBeat=Math.max(0,Number(fromBeat)||0);activeMaxBeat=maxBeat(score);activeBpm=Math.max(20,Math.min(300,Number(score.bpm)||96));activeSpb=60/activeBpm;status('GM-Klänge werden geladen …');await preload(score);const myToken=token;baseTime=ac.currentTime+.08;events=makeEvents(score,activeStartBeat);cursor=0;playerPlaying=true;playerPaused=false;status('▶ Wiedergabe läuft.');scheduleWindow(myToken).catch(err=>status('Player-Fehler: '+(err?.message||err)));updateUi()}
async function consolidatedPause(){if(!playerAudioCtx||!playerPlaying){status('Keine laufende Wiedergabe.');return}if(playerAudioCtx.state==='running'){await playerAudioCtx.suspend();playerPaused=true;status('⏸ Pausiert.')}else{await playerAudioCtx.resume();playerPaused=false;status('▶ Wiedergabe läuft.');scheduleWindow(token).catch(()=>{})}}
function replaceButton(id,handler){const old=$(id);if(!old)return null;const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener('click',handler);return fresh}
function scoreMain(){try{return mainPlayerScore||uploadedScore||lastScore||null}catch(_){return null}}
function scoreTemplate(){try{return window.__sharedCurrentTemplate?.score||null}catch(_){return null}}
function scoreSide(w){try{return window.compositionLabGetComparisonSource?.(w)||null}catch(_){return null}}
function seek(id,scoreFn,target){const r=$(id);if(!r)return;r.onchange=()=>{const sc=scoreFn();if(!sc)return;consolidatedPlay(sc,maxBeat(sc)*(Number(r.value)||0)/1000,target).catch(err=>status('Player-Fehler: '+(err?.message||err)))}}
function syncLoopButtons(){for(const id of ['loopBtn','templateLoopBtn','loopSourceA','loopSourceB']){const b=$(id);if(b)b.textContent=playerLoopEnabled?'🔁 Loop: Ein':'🔁 Loop: Aus'}}
function toggleLoop(){playerLoopEnabled=!playerLoopEnabled;syncLoopButtons();status(playerLoopEnabled?'Loop eingeschaltet.':'Loop ausgeschaltet.')}
function volume(id){const v=$(id);if(!v)return;v.oninput=()=>{const n=Math.max(0,Math.min(100,Number(v.value)||0));try{if(playerMasterGain)playerMasterGain.gain.value=n/100}catch(_){}}}
function install(){try{playGMScore=(score,fromBeat=0)=>consolidatedPlay(score,fromBeat,'main');stopGMPlayback=consolidatedStop;toggleGMPause=consolidatedPause}catch(_){}replaceButton('playBtn',()=>consolidatedPlay(scoreMain(),0,'main').catch(err=>status('Player-Fehler: '+(err?.message||err))));replaceButton('pauseBtn',()=>consolidatedPause().catch(err=>status('Player-Fehler: '+(err?.message||err))));replaceButton('stopBtn',()=>{consolidatedStop(true);resetTimes()});replaceButton('loopBtn',toggleLoop);replaceButton('templatePlayBtn',()=>consolidatedPlay(scoreTemplate(),0,'template').catch(err=>status('Player-Fehler: '+(err?.message||err))));replaceButton('templatePauseBtn',()=>consolidatedPause().catch(()=>{}));replaceButton('templateStopBtn',()=>consolidatedStop(true));replaceButton('templateLoopBtn',toggleLoop);for(const w of ['A','B']){replaceButton('playSource'+w,()=>consolidatedPlay(scoreSide(w),0,w).catch(err=>status('Player-Fehler: '+(err?.message||err))));replaceButton('pauseSource'+w,()=>consolidatedPause().catch(()=>{}));replaceButton('stopSource'+w,()=>consolidatedStop(true));replaceButton('loopSource'+w,toggleLoop);seek('seekSource'+w,()=>scoreSide(w),w);volume('volumeSource'+w)}seek('playerSeek',scoreMain,'main');seek('templateSeek',scoreTemplate,'template');volume('playerVolume');volume('templateVolume');syncLoopButtons();const tech=$('technicalSection')?.querySelector('.foldcontent');if(tech&&!$('consolidatedPlayerBadge')){const d=document.createElement('div');d.id='consolidatedPlayerBadge';d.className='uploadinfo';d.textContent='Player: '+VERSION+' · ein aktiver Wiedergabepfad';tech.appendChild(d)}return !!$('playBtn')}
let tries=0;const t=setInterval(()=>{if(install()||++tries>100)clearInterval(t)},100);
})();
