(()=>{
'use strict';
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
function mode(){if($('technicalSection'))return'root';if($('ipadBuild'))return'ipad';return'rich'}
function interfaceBuild(){return mode()==='root'?26:mode()==='ipad'?16:17}
function interfaceName(){return mode()==='root'?'Android/WebApp':mode()==='ipad'?'iPad':'Mac'}
function gatherUi(){if(mode()==='root')return{interface:interfaceName(),interfaceBuild:interfaceBuild(),provider:$('provider')?.value||'',model:$('model')?.value||'',reasoning:$('reasoningEffort')?.value||'',measures:$('measures')?.value||'',meter:$('meter')?.value||'',tempo:$('tempo')?.value||'',key:$('musicalKey')?.value||'',ensemble:$('ensemble')?.value||'',prompt:$('prompt')?.value||'',templateLength:$('templateLength')?.value||'',labTempo:$('labTempo')?.value||'',labEnsemble:$('labEnsemble')?.value||'',labStyle:$('labStyle')?.value||'',labIdea:$('labIdea')?.value||''};return{interface:interfaceName(),interfaceBuild:interfaceBuild(),provider:$('pageProvider')?.value||state?.provider||'',model:$('pageModel')?.value||state?.model||'',reasoning:$('reasoningStrength')?.value||'',measures:$('length')?.value||'',meter:$('meter')?.value||'',tempo:$('tempo')?.value||'',key:$('keySig')?.value||'',ensemble:$('ensemble')?.value||'',idea:$('compIdea')?.value||'',task:$('compTask')?.value||'',templateLength:$('templateLength')?.value||'',labTempo:$('labTempo')?.value||'',labEnsemble:$('labEnsemble')?.value||'',labStyle:$('labStyle')?.value||'',labIdea:$('labIdea')?.value||''}}
function applyUi(u){if(!u)return;const set=(id,v)=>{const e=$(id);if(e&&v!=null)e.value=v};if(mode()==='root'){set('provider',u.provider);set('model',u.model);set('reasoningEffort',u.reasoning);set('measures',u.measures);set('meter',u.meter);set('tempo',u.tempo);set('musicalKey',u.key);set('ensemble',u.ensemble);set('prompt',u.prompt);set('templateLength',u.templateLength);set('labTempo',u.labTempo);set('labEnsemble',u.labEnsemble);set('labStyle',u.labStyle);set('labIdea',u.labIdea);try{saveCurrentState?.()}catch(_){}}else{set('pageProvider',u.provider);set('pageModel',u.model);set('reasoningStrength',u.reasoning);set('length',u.measures);set('meter',u.meter);set('tempo',u.tempo);set('keySig',u.key);set('ensemble',u.ensemble);set('compIdea',u.idea);set('compTask',u.task);set('templateLength',u.templateLength);set('labTempo',u.labTempo);set('labEnsemble',u.labEnsemble);set('labStyle',u.labStyle);set('labIdea',u.labIdea);try{saveState?.();syncUI?.()}catch(_){}}}
function saveFile(text,name){try{if(typeof downloadBlob==='function'){downloadBlob(text,name,'application/json');return}}catch(_){}if(window.AndroidBridge?.saveBlob){const r=new FileReader();r.onloadend=()=>window.AndroidBridge.saveBlob(r.result,name,'application/json');r.readAsDataURL(new Blob([text],{type:'application/json'}));return}const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function loadRootComposition(pkg){const s=clone(pkg.score);try{lastScore=s;mainPlayerScore=s;lastMidiBytes=buildMidi(s);lastProvider=pkg.provider;lastModel=pkg.model;lastConcept=pkg.idea||s.sm||''}catch(_){}if($('prompt'))$('prompt').value=pkg.task||pkg.idea||s.sm||'';if($('ensemble')&&pkg.settings?.ensemble)$('ensemble').value=pkg.settings.ensemble;if($('tempo'))$('tempo').value=s.bpm||pkg.settings?.bpm||96;if($('meter')&&s.ts)$('meter').value=`${s.ts.n}/${s.ts.d}`;if($('musicalKey'))$('musicalKey').value=s.k||pkg.settings?.key||'frei';if($('mainPlayerTitle'))$('mainPlayerTitle').textContent='Komposition: '+(s.ti||'Unbenannt');try{lastMidiBytes=buildMidi(s);renderChatContext?.();validateScore?.(s);saveCurrentState?.()}catch(_){}if($('status'))$('status').innerHTML='<span class="ok">Komposition aus gemeinsamem Verlauf geladen.</span>'}
function richScore(raw){const s=clone(raw||{});s.tr=Array.isArray(s.tr)?s.tr.map((t,i)=>({nm:t.nm||`Spur ${i+1}`,ch:Number(t.ch??i)%16,pg:Number(t.pg)||0,nt:(Array.isArray(t.nt)?t.nt:[]).map(n=>Array.isArray(n)?{t:Number(n[0])||0,d:Math.max(.03,Number(n[1])||.25),p:Number(n[2]),v:Math.max(1,Math.min(127,Number(n[3])||88)),st:Number(n[4])||0,g:Number(n[5])||.95}:n)})):[];return typeof normalizeScore==='function'?normalizeScore(s):s}
function loadRichComposition(pkg){const s=richScore(pkg.score);state.current=s;state.source=null;if($('compIdea'))$('compIdea').value=pkg.idea||s.sm||'';if($('compTask'))$('compTask').value=pkg.task||'';if($('ensemble')&&pkg.settings?.ensemble)$('ensemble').value=pkg.settings.ensemble;if($('tempo'))$('tempo').value=s.bpm||pkg.settings?.bpm||92;if($('keySig'))$('keySig').value=s.k||pkg.settings?.key||'frei';if($('meter')&&s.ts)$('meter').value=`${s.ts.n}/${s.ts.d}`;try{saveState?.();syncUI?.();openPage?.('composition');setStatus?.('main','Komposition aus gemeinsamem Verlauf geladen.')}catch(_){}}
function renderHistory(S){const box=mode()==='root'?$('historyList'):$('compositionHistory');if(!box)return;const a=S.loadCompositions().slice().reverse();box.innerHTML=a.length?'':'<div class="historyitem">Noch keine Komposition gespeichert.</div>';for(const pkg of a){const d=document.createElement('div');d.className=mode()==='root'?'historyitem':'item';const title=pkg.score?.ti||'Komposition',meta=[pkg.provider,pkg.model,pkg.score?.bpm?pkg.score.bpm+' BPM':''].filter(Boolean).join(' · ');d.innerHTML=`<strong>${String(title).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</strong><div class="historymeta">${meta}</div><div class="historyactions"><button class="secondary smallbtn" data-load="${pkg.id}">In Editor laden</button></div>`;box.appendChild(d)}box.onclick=e=>{const id=e.target?.dataset?.load;if(!id)return;const p=S.loadCompositions().find(x=>x.id===id);if(!p)return;mode()==='root'?loadRootComposition(p):loadRichComposition(p)}}
function install(){const S=window.CompositionLabStorage,E=window.CompositionLabEngine;if(!S||!E)return false;if(window.__compositionLabStorageAdapter)return true;window.__compositionLabStorageAdapter=true;
  if(!E.__sharedStorageWrapped){E.__sharedStorageWrapped=true;const base=E.compose.bind(E);E.compose=async req=>{const r=await base(req);const pkg=S.packageComposition({score:r.score,settings:req.settings||{},idea:r.concept||r.score?.sm||'',task:req.settings?.task||'',provider:req.provider,model:req.model,sourceName:req.sourceName||''});S.addComposition(pkg);r.storagePackageId=pkg.id;setTimeout(()=>renderHistory(S),0);setTimeout(()=>renderHistory(S),250);return r}}
  renderHistory(S);
  const host=mode()==='root'?$('technicalSection')?.querySelector('.foldcontent'):$('techModal')?.querySelector('.modal');if(host&&!$('sharedStoragePanel')){const sec=document.createElement('div');sec.id='sharedStoragePanel';sec.className=mode()==='root'?'':'ipad-tech-section';sec.style.cssText=mode()==='root'?'margin-top:14px;padding-top:12px;border-top:1px solid var(--line,#444)':'';sec.innerHTML=`<h3 style="margin-bottom:7px">Version & Speicherung</h3><div class="uploadinfo"><strong>Engine Build ${S.ENGINE_BUILD}</strong> · Interface Build ${interfaceName()} ${interfaceBuild()}</div><div class="toolbar" style="margin-top:8px"><button type="button" class="secondary smallbtn" id="sharedBackupExport">Sicherung exportieren</button><button type="button" class="secondary smallbtn" id="sharedBackupImport">Sicherung importieren</button><input id="sharedBackupFile" type="file" accept="application/json,.json" style="display:none"></div><div class="uploadinfo">Gemeinsame Sicherung für Kompositionsverlauf, Vorlagenverlauf und nicht geheime Einstellungen. API-Schlüssel werden nicht exportiert.</div>`;const foot=host.querySelector?.('.modalfoot');foot?host.insertBefore(sec,foot):host.appendChild(sec)}
  $('sharedBackupExport')?.addEventListener('click',()=>{const b=S.makeBackup(gatherUi());const stamp=new Date().toISOString().replace(/[:.]/g,'-');saveFile(JSON.stringify(b,null,2),`Composition-Lab-Sicherung-Engine${S.ENGINE_BUILD}-${stamp}.json`)});
  $('sharedBackupImport')?.addEventListener('click',()=>{const f=$('sharedBackupFile');if(f){f.value='';f.click()}});
  $('sharedBackupFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const b=JSON.parse(await f.text());const ui=S.restoreBackup(b);applyUi(ui);renderHistory(S);if(window.CompositionLabExperiment&&Array.isArray(b?.data?.templates)){window.CompositionLabExperiment.saveHistory(b.data.templates);try{window.dispatchEvent(new Event('compositionlab-storage-restored'))}catch(_){}}alert('Sicherung wiederhergestellt.')}catch(err){alert('Wiederherstellung fehlgeschlagen: '+(err?.message||err))}});
  ['backupTechV21','exportBackupBtn','importBackupBtn'].forEach(id=>{const e=$(id);if(e)e.style.display='none'});
  return true;
}
let n=0,t=setInterval(()=>{try{if(install()||++n>400)clearInterval(t)}catch(_){if(++n>400)clearInterval(t)}},100);
})();