from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='''  function useTemplate(){\n    if(!randomTemplateScore) return;\n    uploadedScore = JSON.parse(JSON.stringify(randomTemplateScore));\n    uploadedName = randomTemplateFileName || `${randomTemplateScore.ti}.mid`;\n    const count = (uploadedScore.tr || []).reduce((sum,t) => sum + (t.nt?.length || 0), 0);\n    $("uploadInfo").textContent = `Geladen: ${uploadedName} (${count} Noten) · aus Experimentierlabor`;\n    if(typeof applyTemplateToComposition === "function") applyTemplateToComposition(uploadedScore,{ensemble:$("labInstrumentCombo")?.value||""});\n    saveCurrentState();\n    if($("experimentSection")) $("experimentSection").open = false;\n    $("status").innerHTML = `<span class="ok">„${esc(randomTemplateScore.ti)}“ wurde als Vorlage in die eigentliche Komposition übernommen.</span>`;\n  }'''
new='''  function useTemplate(){\n    if(!randomTemplateScore) return;\n    uploadedScore = JSON.parse(JSON.stringify(randomTemplateScore));\n    uploadedName = randomTemplateFileName || `${randomTemplateScore.ti}.mid`;\n    const count = (uploadedScore.tr || []).reduce((sum,t) => sum + (t.nt?.length || 0), 0);\n    if(typeof window.compositionLabApplyTemplate === "function") {\n      window.compositionLabApplyTemplate(uploadedScore,{\n        ensemble: $("labInstrumentCombo")?.value || "",\n        idea: uploadedScore.sm || ""\n      });\n    } else {\n      const ts = uploadedScore.ts || {n:4,d:4};\n      $("meter").value = `${Number(ts.n)||4}/${Number(ts.d)||4}`;\n      $("tempo").value = Number(uploadedScore.bpm)||96;\n      $("musicalKey").value = uploadedScore.k||"C major";\n      $("ensemble").value = $("labInstrumentCombo")?.value || (uploadedScore.tr||[]).map(t=>t.nm).filter(Boolean).join(" + ") || $("ensemble").value;\n      $("prompt").value = `Vorlage: ${uploadedScore.ti||"Vorlage"}. ${uploadedScore.sm||"Entwickle den musikalischen Grundgedanken der Vorlage weiter."}`;\n    }\n    $("uploadInfo").textContent = `Geladen: ${uploadedName} (${count} Noten) · aus Experimentierlabor`;\n    saveCurrentState();\n    $("status").innerHTML = `<span class="ok">„${esc(randomTemplateScore.ti)}“ wurde mit Einstellungen und Kompositionsidee übernommen. Das Experimentierlabor bleibt unverändert geöffnet oder geschlossen.</span>`;\n  }'''
if old not in s:
    raise SystemExit('useTemplate block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
